import pandas as pd
import jsonlines
import random
import string
from pathlib import Path

# Resolve paths from this script's location so it runs from any working
# directory and always writes inside its own study folder.
SCRIPT_DIR = Path(__file__).resolve().parent

# NOTE: processed_data/exp*.csv are semicolon-delimited and carry an `age`
# column that preprocess_data.py does not produce. The committed CSVs were
# generated by a later version of that script than the one in this repo, so
# the preprocess -> generate chain does not round-trip. This reads the
# committed files as they actually are; resolving the mismatch needs the
# original contributor.

#Define the path
path = SCRIPT_DIR / "prompts.jsonl"

#Load preprocessed files from Exp1 and Exp2
df1 = pd.read_csv(SCRIPT_DIR / "processed_data" / "exp1.csv", sep=';')
df2 = pd.read_csv(SCRIPT_DIR / "processed_data" / "exp2.csv", sep=';')

#Merge the two dataframes
df = pd.concat([df1, df2], ignore_index=True)

# Get unique participants and trial indices
participants = df['participant_id'].unique() #This puts each participant in a separate column
trials = range(df['trial_id'].max() + 1)

#Recode response keys
df["response"] = df["response"].map({1: "a", 2: "l"})

#Recode accuracy
df["accuracy"] = df["accuracy"].map({1: "1", 0: "0", 3: "2"})

# Generate individual prompts for each participant
all_prompts = []

#Define response options/choices
choices = ("a", "l")  # fixed keys

for participant in participants:
    df_participant = df[df['participant_id'] == participant]

    if df_participant.empty:
        continue  # safety

    participant = participant.item()
    age = df_participant['age'].iloc[0].item()

    rt_list = []
    accuracy_list = []

    prompt = f"""In questo studio vi verranno mostrati diversi stimoli sullo schermo. Il vostro compito è quello di determinare se si tratta di una parola italiana esistente o meno.\n 
Se pensate che sia una parola italiana esistente, premete il tasto {choices[0]}, mentre se pensate che non sia una parola italiana esistente, premete il tasto {choices[1]}.\n
Ignorate il colore dello stimolo e concentratevi sull'esistenza o meno della parola in italiano.\n"""

    for _, row in df_participant.iterrows():
        word = row['stimulus']
        response = row['response']

        prompt += f'The word "{word}" appears on the screen. You press <<{response}>>.\n'
        rt_list.append(row['rt'])
        accuracy_list.append(row['accuracy'])

    all_prompts.append({
        'text': prompt,
        'experiment': 'Saban_ItalianLDT-Exp1',
        'participant_id': participant,
        'age': age,
        'rt': rt_list,
        'accuracy': accuracy_list
    })

#Save all prompts to JSONL file
with jsonlines.open(path, mode='w') as writer:
    writer.write_all(all_prompts)
